# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Set the version
      run: |
        echo "version=`date -u +%F_%T_`${{ github.sha }}" >> $GITHUB_ENV
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Replace Version
      # You may pin to the exact commit or the version.
      # uses: visiosto/replace-value@7f3c03b1e89bac94997b4cac35d56b97c4eb4ebf
      uses: visiosto/replace-value@v1.2.1
      with:
        # The file where the content to replace is.
        file: public/index.html
        # The value that will be replaced.
        replaced: VERSION_PLACEHOLDER
        # The value that the original value is replaced with.
        value: ${{ env.version }}
    - run: npm ci
    - run: npm run build --if-present
#     - run: npm test
    - name: Pushes to another repository
      uses: cpina/github-action-push-to-another-repository@v1.5.1
      env:
        SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
      with:
        source-directory: 'build'
        destination-github-username: 'zgldh'
        destination-repository-name: 'zgldh.github.io'
        user-email: zgldh@hotmail.com
        target-branch: master
